### ISSUE TITLE
why combine overseas and mainland together?

### ISSUE THREAD

**Issue by l89669** [JasonKhew96/bangumi#6]

**Comment by JasonKhew96** [comment]
@l89669 

Due to old title messing up data, e.g. "成神之日", "满溢的水果塔", etc. (They are overseas title, but moved to bilibili SEA, but some data still can access from main bilibili API, but you can only watch it from bilibili SEA), I decided to merged it.

(Something like "Running Man" entertainment series also included but it's overseas title)

You can just search "仅" to filter out some overseas title.

**Comment by l89669** [comment]
Then I suggest add basic attributes like forms(anims, TV series, etc.), years, and add filters for users. Or at least add thumbnails for users to preview.
